packages:
  - '.'

engineStrict: true
registries:
  '@kartore-internal': https://npm.pkg.github.com/

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
configDependencies:
  '@pnpm/pacquet': 0.11.12
minimumReleaseAgeExclude:
  - '@kartore-internal/github-adapter'
  - '@kartore/file-adapter'
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - workerd
  - sharp
  - esbuild
