engineStrict: true
registries:
  '@kartore-internal': https://npm.pkg.github.com/

enableGlobalVirtualStore: true

configDependencies:
  '@pnpm/pacquet': 0.11.12

packageExtensions:
  '@sveltejs/kit@3.0.0-next.8':
    dependencies:
      rolldown: ^1.1.2

minimumReleaseAgeExclude:
  - '@kartore-internal/github-adapter'
  - '@kartore/file-adapter'
allowBuilds:
  esbuild: false
  sharp: false
  workerd: false
